from abc import ABC, abstractmethod

class DataAnalysis(ABC):
        """The abstract base class for all data analyses. Methods cover
        the execution of analyses, rendering, and exporting of data."""
        
        @abstractmethod
        def canHandleRequest(self,request):
                """
                Returns True if the routine is capable of handling the request (i.e. the
                RequestModel is of the type that the analysis expects), and False otherwise.
                """
                pass
        
        @abstractmethod      
        def getRequestType(self):
                """
                Returns the class object for the routine's companion request type.
                """
                pass
                
        @abstractmethod
        def execute(self,request):
                """
                Contains the code for processing data generated by mining routines and/or from external
                databases.
                
                Parameters:
                        request (@input): A RequestModel object that encapsulates all the information needed
                        to run the analysis.
                
                """
                pass
        
        """      
        @abstractmethod       
        def export(self,request,response):
                Contains the code for exporting data to a file. To have output data logged in provenance records
                the export method must add ReposcannerDataEntity objects as attachments to the response.
                
                Parameters:
                        request (@input): A RequestModel object that encapsulates all the information needed
                        to run the analysis.
                
                        response (@input): A ResponseModel object. If the routine was successful, then
                        the response will contain the data generated by the execute() method as an attachment.
                pass
        """
                
        def run(self,request):
                """
                Encodes the workflow of a RepositoryRoutine object. The client only needs
                to run this method in order to get results. 
                """
                response = self.execute(request,dataset)
                #self.export(request,response)
                return response